- name: Set up Arma3 group.
  group:
    name: "{{ arma3_group }}"
    state: present

- name: Set up Arma3 user.
  user:
    name: "{{ arma3_user }}"
    comment: Arma3 server user.
    group: "{{ arma3_group }}"
    state: present

- name: Donwload LinuxGSM script for Arma3 deployment.
  become: true
  become_user: "{{ arma3_user }}"
  get_url:
       url: https://linuxgsm.sh
       dest: "/home/{{ arma3_user }}/linuxgsm.sh"
       mode: +x
       group: "{{ arma3_group }}"
       owner: "{{ arma3_user }}"